export const BASE_API_URL = 'http://192.168.5.17:5172/api/';
export const BASE_URL = 'http://192.168.5.17:5172/';
export const USERS_API='users';
export const POST_LOGIN_API='login';
export const POST_LOGOUT_API='logout';
export const POST_REGISTER_API='register';
export const PRODUCTS_API='products';
export const CATEGORIES_API='categories';
export const CATEGORY_API='category';